import type { User } from '../models/User';

/** Dữ liệu mẫu — thay bằng truy vấn DB sau khi kết nối MySQL. */
export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Nguyễn Văn Admin',
    email: 'admin@ptit.edu.vn',
    role: 'admin',
    department: 'Ban Quản Trị',
    reputation: 9999,
    posts: 150,
    answers: 320,
    votes: 1250,
    followers: 500,
    following: 50,
    joinDate: '2023-01-01',
    badges: ['admin', 'top-contributor', 'helpful'],
    status: 'active',
  },
  {
    id: '2',
    name: 'Trần Thị Hương',
    email: 'huong@student.ptit.edu.vn',
    role: 'student',
    department: 'Công Nghệ Thông Tin',
    major: 'Lập Trình Web',
    studentId: 'B21DCCN123',
    bio: 'Sinh viên năm 3 ngành CNTT, đam mê Web Development và AI',
    reputation: 1250,
    posts: 28,
    answers: 45,
    votes: 320,
    followers: 89,
    following: 34,
    joinDate: '2024-09-01',
    badges: ['first-question', 'helpful', '100-votes'],
    status: 'active',
  },
  {
    id: '3',
    name: 'PGS.TS Lê Minh Đức',
    email: 'duc.lm@ptit.edu.vn',
    role: 'teacher',
    department: 'Khoa CNTT',
    major: 'Khoa học máy tính',
    bio: 'Giảng viên môn CTDL, Giải Thuật, AI. Có 15 năm kinh nghiệm giảng dạy.',
    reputation: 5430,
    posts: 85,
    answers: 210,
    votes: 870,
    followers: 342,
    following: 15,
    joinDate: '2023-06-15',
    badges: ['teacher', 'expert', 'top-contributor', 'advisor'],
    status: 'active',
  },
];

/** Danh sách admin (bảng Users) — mở rộng từ seed gốc Admin/Users.tsx */
export const MOCK_ADMIN_USERS: User[] = [
  ...MOCK_USERS,
  {
    id: '4',
    name: 'Hoàng Văn Bình',
    email: 'binh@student.ptit.edu.vn',
    role: 'student',
    reputation: 980,
    posts: 35,
    answers: 0,
    votes: 0,
    followers: 0,
    following: 0,
    joinDate: '20/09/2024',
    badges: [],
    status: 'banned',
  },
  {
    id: '5',
    name: 'Nguyễn Minh Châu',
    email: 'chau@ptit.edu.vn',
    role: 'teacher',
    reputation: 870,
    posts: 42,
    answers: 0,
    votes: 0,
    followers: 0,
    following: 0,
    joinDate: '01/08/2023',
    badges: [],
    status: 'active',
  },
  {
    id: '6',
    name: 'Phạm Thị Lan',
    email: 'lan@student.ptit.edu.vn',
    role: 'student',
    reputation: 320,
    posts: 8,
    answers: 0,
    votes: 0,
    followers: 0,
    following: 0,
    joinDate: '05/10/2024',
    badges: [],
    status: 'active',
  },
];
